language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq check flex bison libtool
  - sudo apt-get install -qq libdbi-dev libedit-dev libltdl-dev
  - sudo pip install cpp-coveralls --use-mirrors
before_script:
  - ./autogen.sh
script: ./configure --enable-gcov CFLAGS="-O0 -Wno-sign-conversion" && make && make test
after_success:
  - coveralls --exclude t --verbose
branches:
  only:
    - master
